apiVersion: apps/v1
kind: Deployment                                            # 1
metadata:
  name: sc-admin-deployment
spec:
  selector:
    matchLabels:
      app: admin
  replicas: 1
  minReadySeconds: 15
  strategy:
    type: RollingUpdate                                   # 3
    rollingUpdate:
      maxUnavailable: 1                                   # 4
      maxSurge: 1
  template:                                               # 6
    metadata:
      labels:
        app: admin
    spec:
      volumes:
        - name: faces-storage
          persistentVolumeClaim:
            claimName: faces-claim
      containers:
        - image: siriusadmin_web # 4
          imagePullPolicy: IfNotPresent
          name: sc-admin-pod
          env:
          - name: "DB_HOST"
            value: "10.25.61.12"
          - name: "DB_NAME"
            value: "smc"
          - name: "DB_USER"
            value: "smc"
          - name: "DB_PASSWORD"
            value: "wUqbfGC6wCRORJD3bhYHQ9cfg4ACDNH5"
          - name: "LOGS"
            value: "./temp"
          ports:
            - containerPort: 8000
          volumeMounts:
            - mountPath: "/profiles"
              name: faces-storage
---
apiVersion: v1
kind: Service
metadata:
  name: sc-admin-np
spec:
  type: ClusterIP
  selector:
    app: admin
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 8000
      targetPort: 8000
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
     
