version: "3.3"

services:
  web:
    build: ./src/smartcity/
    restart: always
    environment:
      DB_HOST: "10.25.61.12"
      DB_NAME: "smc"
      DB_USER: "smc"
      DB_PASSWORD: "wUqbfGC6wCRORJD3bhYHQ9cfg4ACDNH5"
      LOGS: "./temp"
  nginx:
    image: nginx:1.19.2
    restart: always
    volumes:
      - ./src/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./src/nginx/configs:/etc/nginx/conf.d:ro
      - /home/letsencrypt/.acme.sh/smart.parksirius.ru/:/ssl/
      - static_content:/data
    depends_on:
      - web
    ports:
      - "30004:80"
volumes:
  static_content: