apiVersion: v1
kind: PersistentVolume
metadata:
  name: faces-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/kuber/profiles"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: faces-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi